#!/usr/bin/env bash

set -euo pipefail


# =========================================================
# Path Configuration
# =========================================================

SCRIPT_DIR="$(
  cd "$(dirname "${BASH_SOURCE[0]}")"
  pwd
)"

TERRAFORM_DIR="$(
  cd "${SCRIPT_DIR}/.."
  pwd
)"

PROJECT_ROOT="$(
  cd "${TERRAFORM_DIR}/.."
  pwd
)"

ANSIBLE_DIR="${PROJECT_ROOT}/ansible"

GENERATED_VARS_FILE="${ANSIBLE_DIR}/vars/terraform.yml"


# =========================================================
# Start
# =========================================================

echo
echo "========================================"
echo " Generate Ansible Variables"
echo "========================================"


# =========================================================
# 1. Check Terraform Output
# =========================================================

if ! terraform -chdir="${TERRAFORM_DIR}" \
  output thanos_s3_bucket_name >/dev/null 2>&1; then

  echo
  echo "[ERROR] Terraform output not found:"
  echo "        thanos_s3_bucket_name"
  echo
  echo "[ERROR] Run terraform apply first."

  exit 1
fi


# =========================================================
# 2. Read Terraform Output
# =========================================================

THANOS_S3_BUCKET_NAME="$(
  terraform -chdir="${TERRAFORM_DIR}" \
    output -raw thanos_s3_bucket_name
)"


if [[ -z "${THANOS_S3_BUCKET_NAME}" ]]; then

  echo
  echo "[ERROR] thanos_s3_bucket_name is empty."

  exit 1
fi


# =========================================================
# 3. Ensure Ansible vars Directory Exists
# =========================================================

mkdir -p "$(dirname "${GENERATED_VARS_FILE}")"


# =========================================================
# 4. Generate Ansible Variable File
# =========================================================

cat > "${GENERATED_VARS_FILE}" <<EOF
---
# Generated automatically from Terraform outputs.
#
# DO NOT EDIT THIS FILE MANUALLY.

thanos_s3_bucket_name: "${THANOS_S3_BUCKET_NAME}"
EOF


# =========================================================
# 5. Result
# =========================================================

echo
echo "[INFO] Generated Ansible variable file:"
echo "       ${GENERATED_VARS_FILE}"

echo
echo "[INFO] Terraform values:"
echo "       thanos_s3_bucket_name=${THANOS_S3_BUCKET_NAME}"

echo
echo "========================================"
echo " Ansible Variables Generated Successfully"
echo "========================================"
echo