---
# Kubernetes Pod 네트워크
pod_network_cidr: "192.168.0.0/16"

# kubeadm 관리자 kubeconfig
kubeconfig_path: /etc/kubernetes/admin.conf

# ubuntu 사용자 kubeconfig
kubernetes_admin_user: ubuntu
kubernetes_user_kubeconfig: /home/ubuntu/.kube/config

# Helm
helm_binary_path: /usr/local/bin/helm

# Calico
calico_version: "v3.32.0"

calico_repository_name: projectcalico
calico_repository_url: https://docs.tigera.io/calico/charts

calico_crd_chart: projectcalico/crd.projectcalico.org.v1
calico_operator_chart: projectcalico/tigera-operator

calico_release_name: calico
calico_release_namespace: tigera-operator

calico_values_remote_path: /tmp/calico-values.yml

calico_encapsulation: VXLANCrossSubnet

# Metrics Server
metrics_server_repository_name: metrics-server
metrics_server_repository_url: https://kubernetes-sigs.github.io/metrics-server/

metrics_server_chart: metrics-server/metrics-server
metrics_server_chart_version: "3.13.1"

metrics_server_release_name: metrics-server
metrics_server_release_namespace: kube-system

# kubeadm의 기본 kubelet serving certificate는 self-signed이므로
# 학습 환경에서 임시로 TLS 인증서 검증을 비활성화한다.
metrics_server_extra_args:
  - --kubelet-insecure-tls