---
# Cluster
cluster_name: ksh-k8s

# Kubernetes Pod 네트워크
pod_network_cidr: "192.168.0.0/16"

# kubeadm 관리자 kubeconfig
kubeconfig_path: /etc/kubernetes/admin.conf

# ubuntu 사용자 kubeconfig
kubernetes_admin_user: ubuntu
kubernetes_user_kubeconfig: /home/ubuntu/.kube/config

# Helm
helm_binary_path: /usr/local/bin/helm

# Calico
calico_version: "v3.32.0"

calico_repository_name: projectcalico
calico_repository_url: https://docs.tigera.io/calico/charts

calico_crd_chart: projectcalico/crd.projectcalico.org.v1
calico_operator_chart: projectcalico/tigera-operator

calico_release_name: calico
calico_release_namespace: tigera-operator

calico_values_remote_path: /tmp/calico-values.yml

calico_encapsulation: VXLAN

# Metrics Server
metrics_server_repository_name: metrics-server
metrics_server_repository_url: https://kubernetes-sigs.github.io/metrics-server/

metrics_server_chart: metrics-server/metrics-server
metrics_server_chart_version: "3.13.1"

metrics_server_release_name: metrics-server
metrics_server_release_namespace: kube-system

# kubeadm의 기본 kubelet serving certificate는 self-signed이므로
# 학습 환경에서 임시로 TLS 인증서 검증을 비활성화한다.
metrics_server_extra_args:
  - --kubelet-insecure-tls

# AWS
aws_region: ap-northeast-2
aws_cli_profile: default

# ASG Worker bootstrap
ssm_join_command_parameter: /ksh/k8s/join-command

# Cluster Autoscaler
cluster_autoscaler_repository_name: autoscaler
cluster_autoscaler_repository_url: https://kubernetes.github.io/autoscaler

cluster_autoscaler_chart: autoscaler/cluster-autoscaler
cluster_autoscaler_chart_version: "9.58.0"

cluster_autoscaler_release_name: cluster-autoscaler
cluster_autoscaler_release_namespace: kube-system

cluster_autoscaler_values_remote_path: /tmp/cluster-autoscaler-values.yml

cluster_autoscaler_image_tag: "v1.36.0"