---
- name: Configure common prerequisites on all Kubernetes nodes
  ansible.builtin.import_playbook: common.yml

- name: Initialize Kubernetes control plane
  ansible.builtin.import_playbook: master.yml

- name: Install Helm on Kubernetes control plane
  ansible.builtin.import_playbook: helm.yml

- name: Install Kubernetes cluster add-ons
  ansible.builtin.import_playbook: addons.yml

- name: Join worker nodes to Kubernetes cluster
  ansible.builtin.import_playbook: workers.yml