---
- name: Configure common prerequisites on all Kubernetes nodes
  ansible.builtin.import_playbook: common.yml

- name: Initialize Kubernetes control plane
  ansible.builtin.import_playbook: master.yml

- name: Publish kubeadm join command for ASG worker nodes
  ansible.builtin.import_playbook: publish-join-command.yml

- name: Install Helm on Kubernetes control plane
  ansible.builtin.import_playbook: helm.yml

- name: Install Kubernetes cluster add-ons
  ansible.builtin.import_playbook: addons.yml

- name: Join worker nodes to Kubernetes cluster
  ansible.builtin.import_playbook: workers.yml

- name: Install Kubernetes Metrics Server
  ansible.builtin.import_playbook: metrics-server.yml