---
- name: Configure common prerequisites on all Kubernetes nodes
  ansible.builtin.import_playbook: common.yml

- name: Initialize Kubernetes control plane
  ansible.builtin.import_playbook: master.yml

- name: Publish kubeadm join command for ASG worker nodes
  ansible.builtin.import_playbook: publish-join-command.yml

- name: Install Helm on Kubernetes control plane
  ansible.builtin.import_playbook: helm.yml

- name: Install Kubernetes cluster add-ons
  ansible.builtin.import_playbook: addons.yml

- name: Join worker nodes to Kubernetes cluster
  ansible.builtin.import_playbook: workers.yml

- name: Configure AWS provider IDs for Kubernetes nodes
  ansible.builtin.import_playbook: configure-node-provider-id.yml

- name: Install Kubernetes Metrics Server
  ansible.builtin.import_playbook: metrics-server.yml

- name: Install Kubernetes Cluster Autoscaler
  ansible.builtin.import_playbook: cluster-autoscaler.yml

- name: Install ingress-nginx Ingress Controller
  ansible.builtin.import_playbook: ingress-nginx.yml

- name: Install Gateway API CRDs
  ansible.builtin.import_playbook: gateway-api-install.yml

- name: Install AWS Load Balancer Controller
  ansible.builtin.import_playbook: aws-load-balancer-controller.yml

- name: Install AWS EBS CSI Driver
  ansible.builtin.import_playbook: ebs-csi-driver.yml

- name: Install Kubernetes monitoring stack
  ansible.builtin.import_playbook: monitoring.yml

- name: Install Thanos Store Gateway
  ansible.builtin.import_playbook: thanos-store-gateway.yml

- name: Install Thanos Query
  ansible.builtin.import_playbook: thanos-query.yml

- name: Install Thanos Compactor
  ansible.builtin.import_playbook: thanos-compactor.yml

- name: Install Loki logging stack
  ansible.builtin.import_playbook: loki.yml

- name: Install Grafana Alloy
  ansible.builtin.import_playbook: alloy.yml

- name: Install Grafana Alloy Kubernetes event collector
  ansible.builtin.import_playbook: alloy-events.yml